/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ibm.tw.cos.app;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Stream;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.web.client.HttpClientErrorException;

import com.ibm.tw.cloud.iam.IBMCloudTokenGenerator;
import com.ibm.tw.cloud.os.domain.Bucket;
import com.ibm.tw.cloud.os.domain.ListBucketResult;
import com.ibm.tw.cloud.os.service.CloudObjectStorageService;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication(scanBasePackages={"com.ibm.tw.cloud","com.ibm.tw.cos.app"})
public class App {

private final Logger logger = LoggerFactory.getLogger(getClass());
	
    @Autowired
    @Qualifier("restTemplate")
    CloudObjectStorageService restTemplateCOSService;

    @Autowired
    IBMCloudTokenGenerator tokenGenerator;

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        App app = new App();
        System.out.println(app.getGreeting());
	app.tokenGenerator.generateToken(System.getenv("IBM_S3_API_KEY"));
	System.out.println(app.tokenGenerator.getToken());
    }
}
